# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visivel', models.BooleanField(max_length=128)),
                ('nome', models.CharField(max_length=128)),
                ('descricacao', models.CharField(max_length=256)),
                ('institucional', models.BooleanField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Compromissos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricacao', models.CharField(max_length=256)),
                ('agendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agendas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('agendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agendas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('agendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agendas')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCompromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('confirmacao', models.BooleanField(max_length=128)),
                ('compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromissos')),
            ],
        ),
        migrations.AddField(
            model_name='agendas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
